### ISSUE TITLE
Meteor.loginWithWechatMP callback is never called

### ISSUE THREAD

**Issue by deeeed** [zhaoyao91/meteor-accounts-wechat-mp#3] opened 2017-02-16 04:20 UTC
I have been playing around with the lib and found a couple of problems.
First of all, the package zhaoyao91:short-oauth-state should be made mandatory, I knocked my head on the wall to find out why weixin was refusing my requests.

Another problem is that my callback in Meteor.loginWithWechatMP(function callback(err) {
// never executed...
});

I does work for well for the open platform with loginWithWechat().

At the moment I directly hacked the Oauth package overwritting OAuth.getDataAfterRedirect to detect the return from weixin. It works but it's definitely not a good practice...

Is the callback working for you ?

**Comment by zhaoyao91** [comment] 2017-02-16 09:16
I didn't test it, but I thought the problem is probably caused by the `loginStyle: redirect`. Because you referesh the page after login, all the registered callbacks will be losed.
Sadly, for some reason (by the time I made this package) you can only login with `redicrect` style because the wechat browser has some limitation. I am not sure if they have improved it. You can have a try to set the loginStyle to popup to see if it works right now.

**Comment by zhaoyao91** [comment] 2017-02-16 09:19
The reason for I didn't make the short-oauth-state packge mandatory is that I thought it's just a workaround, so I expect there to be some better solution and I didn't want to force user to use it.

**Comment by deeeed** [comment] 2017-02-17 04:02
I would recommend to update the documentation to explain what "short-oauth-package" is used for. Otherwise people (like me) may spend a lot of time trying to debug it without understanding why it doesn't work.
Thanks for your package anyway ;)

**Comment by zhaoyao91** [comment] 2017-02-17 15:20
Thanks for your suggestion. I have updated the docs and will close this issue. If you still have any related problem, feel free to reopen it.

**Closed as completed by zhaoyao91** 2017-02-17 15:20 UTC
